# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rfcontrol_pb2 as rfcontrol__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in rfcontrol_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RFControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetRFSettings = channel.unary_unary(
                '/rfcontrol.RFController/SetRFSettings',
                request_serializer=rfcontrol__pb2.RFConfig.SerializeToString,
                response_deserializer=rfcontrol__pb2.RFResponse.FromString,
                _registered_method=True)
        self.GetCurrentSettings = channel.unary_unary(
                '/rfcontrol.RFController/GetCurrentSettings',
                request_serializer=rfcontrol__pb2.DeviceQuery.SerializeToString,
                response_deserializer=rfcontrol__pb2.CurrentSettings.FromString,
                _registered_method=True)


class RFControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetRFSettings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentSettings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RFControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetRFSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRFSettings,
                    request_deserializer=rfcontrol__pb2.RFConfig.FromString,
                    response_serializer=rfcontrol__pb2.RFResponse.SerializeToString,
            ),
            'GetCurrentSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentSettings,
                    request_deserializer=rfcontrol__pb2.DeviceQuery.FromString,
                    response_serializer=rfcontrol__pb2.CurrentSettings.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rfcontrol.RFController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rfcontrol.RFController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RFController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetRFSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rfcontrol.RFController/SetRFSettings',
            rfcontrol__pb2.RFConfig.SerializeToString,
            rfcontrol__pb2.RFResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrentSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rfcontrol.RFController/GetCurrentSettings',
            rfcontrol__pb2.DeviceQuery.SerializeToString,
            rfcontrol__pb2.CurrentSettings.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
