
services:
  server:
    build: .
    ports:
      - "50051:50051"
    networks:
      - rf-network

  # client:
  #   build: ./client
  #   depends_on:
  #     - server
  #   networks:
  #     - rf-network
  #   stdin_open: true
  #   tty: true


networks:
  rf-network:
    driver: bridge
