// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: rfcontrol.proto
#ifndef GRPC_rfcontrol_2eproto__INCLUDED
#define GRPC_rfcontrol_2eproto__INCLUDED

#include "rfcontrol.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace rfcontrol {

class RFController final {
 public:
  static constexpr char const* service_full_name() {
    return "rfcontrol.RFController";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SetRFSettings(::grpc::ClientContext* context, const ::rfcontrol::RFConfig& request, ::rfcontrol::RFResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rfcontrol::RFResponse>> AsyncSetRFSettings(::grpc::ClientContext* context, const ::rfcontrol::RFConfig& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rfcontrol::RFResponse>>(AsyncSetRFSettingsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rfcontrol::RFResponse>> PrepareAsyncSetRFSettings(::grpc::ClientContext* context, const ::rfcontrol::RFConfig& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rfcontrol::RFResponse>>(PrepareAsyncSetRFSettingsRaw(context, request, cq));
    }
    virtual ::grpc::Status GetCurrentSettings(::grpc::ClientContext* context, const ::rfcontrol::DeviceQuery& request, ::rfcontrol::CurrentSettings* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rfcontrol::CurrentSettings>> AsyncGetCurrentSettings(::grpc::ClientContext* context, const ::rfcontrol::DeviceQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rfcontrol::CurrentSettings>>(AsyncGetCurrentSettingsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rfcontrol::CurrentSettings>> PrepareAsyncGetCurrentSettings(::grpc::ClientContext* context, const ::rfcontrol::DeviceQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::rfcontrol::CurrentSettings>>(PrepareAsyncGetCurrentSettingsRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void SetRFSettings(::grpc::ClientContext* context, const ::rfcontrol::RFConfig* request, ::rfcontrol::RFResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SetRFSettings(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::rfcontrol::RFResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void SetRFSettings(::grpc::ClientContext* context, const ::rfcontrol::RFConfig* request, ::rfcontrol::RFResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void SetRFSettings(::grpc::ClientContext* context, const ::rfcontrol::RFConfig* request, ::rfcontrol::RFResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void SetRFSettings(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::rfcontrol::RFResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void SetRFSettings(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::rfcontrol::RFResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void GetCurrentSettings(::grpc::ClientContext* context, const ::rfcontrol::DeviceQuery* request, ::rfcontrol::CurrentSettings* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetCurrentSettings(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::rfcontrol::CurrentSettings* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetCurrentSettings(::grpc::ClientContext* context, const ::rfcontrol::DeviceQuery* request, ::rfcontrol::CurrentSettings* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetCurrentSettings(::grpc::ClientContext* context, const ::rfcontrol::DeviceQuery* request, ::rfcontrol::CurrentSettings* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetCurrentSettings(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::rfcontrol::CurrentSettings* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetCurrentSettings(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::rfcontrol::CurrentSettings* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rfcontrol::RFResponse>* AsyncSetRFSettingsRaw(::grpc::ClientContext* context, const ::rfcontrol::RFConfig& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rfcontrol::RFResponse>* PrepareAsyncSetRFSettingsRaw(::grpc::ClientContext* context, const ::rfcontrol::RFConfig& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rfcontrol::CurrentSettings>* AsyncGetCurrentSettingsRaw(::grpc::ClientContext* context, const ::rfcontrol::DeviceQuery& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::rfcontrol::CurrentSettings>* PrepareAsyncGetCurrentSettingsRaw(::grpc::ClientContext* context, const ::rfcontrol::DeviceQuery& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status SetRFSettings(::grpc::ClientContext* context, const ::rfcontrol::RFConfig& request, ::rfcontrol::RFResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rfcontrol::RFResponse>> AsyncSetRFSettings(::grpc::ClientContext* context, const ::rfcontrol::RFConfig& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rfcontrol::RFResponse>>(AsyncSetRFSettingsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rfcontrol::RFResponse>> PrepareAsyncSetRFSettings(::grpc::ClientContext* context, const ::rfcontrol::RFConfig& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rfcontrol::RFResponse>>(PrepareAsyncSetRFSettingsRaw(context, request, cq));
    }
    ::grpc::Status GetCurrentSettings(::grpc::ClientContext* context, const ::rfcontrol::DeviceQuery& request, ::rfcontrol::CurrentSettings* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rfcontrol::CurrentSettings>> AsyncGetCurrentSettings(::grpc::ClientContext* context, const ::rfcontrol::DeviceQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rfcontrol::CurrentSettings>>(AsyncGetCurrentSettingsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rfcontrol::CurrentSettings>> PrepareAsyncGetCurrentSettings(::grpc::ClientContext* context, const ::rfcontrol::DeviceQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::rfcontrol::CurrentSettings>>(PrepareAsyncGetCurrentSettingsRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void SetRFSettings(::grpc::ClientContext* context, const ::rfcontrol::RFConfig* request, ::rfcontrol::RFResponse* response, std::function<void(::grpc::Status)>) override;
      void SetRFSettings(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::rfcontrol::RFResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void SetRFSettings(::grpc::ClientContext* context, const ::rfcontrol::RFConfig* request, ::rfcontrol::RFResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void SetRFSettings(::grpc::ClientContext* context, const ::rfcontrol::RFConfig* request, ::rfcontrol::RFResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void SetRFSettings(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::rfcontrol::RFResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void SetRFSettings(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::rfcontrol::RFResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void GetCurrentSettings(::grpc::ClientContext* context, const ::rfcontrol::DeviceQuery* request, ::rfcontrol::CurrentSettings* response, std::function<void(::grpc::Status)>) override;
      void GetCurrentSettings(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::rfcontrol::CurrentSettings* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetCurrentSettings(::grpc::ClientContext* context, const ::rfcontrol::DeviceQuery* request, ::rfcontrol::CurrentSettings* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetCurrentSettings(::grpc::ClientContext* context, const ::rfcontrol::DeviceQuery* request, ::rfcontrol::CurrentSettings* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetCurrentSettings(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::rfcontrol::CurrentSettings* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetCurrentSettings(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::rfcontrol::CurrentSettings* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::rfcontrol::RFResponse>* AsyncSetRFSettingsRaw(::grpc::ClientContext* context, const ::rfcontrol::RFConfig& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rfcontrol::RFResponse>* PrepareAsyncSetRFSettingsRaw(::grpc::ClientContext* context, const ::rfcontrol::RFConfig& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rfcontrol::CurrentSettings>* AsyncGetCurrentSettingsRaw(::grpc::ClientContext* context, const ::rfcontrol::DeviceQuery& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::rfcontrol::CurrentSettings>* PrepareAsyncGetCurrentSettingsRaw(::grpc::ClientContext* context, const ::rfcontrol::DeviceQuery& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SetRFSettings_;
    const ::grpc::internal::RpcMethod rpcmethod_GetCurrentSettings_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SetRFSettings(::grpc::ServerContext* context, const ::rfcontrol::RFConfig* request, ::rfcontrol::RFResponse* response);
    virtual ::grpc::Status GetCurrentSettings(::grpc::ServerContext* context, const ::rfcontrol::DeviceQuery* request, ::rfcontrol::CurrentSettings* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SetRFSettings : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SetRFSettings() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SetRFSettings() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetRFSettings(::grpc::ServerContext* /*context*/, const ::rfcontrol::RFConfig* /*request*/, ::rfcontrol::RFResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetRFSettings(::grpc::ServerContext* context, ::rfcontrol::RFConfig* request, ::grpc::ServerAsyncResponseWriter< ::rfcontrol::RFResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetCurrentSettings : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetCurrentSettings() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetCurrentSettings() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCurrentSettings(::grpc::ServerContext* /*context*/, const ::rfcontrol::DeviceQuery* /*request*/, ::rfcontrol::CurrentSettings* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetCurrentSettings(::grpc::ServerContext* context, ::rfcontrol::DeviceQuery* request, ::grpc::ServerAsyncResponseWriter< ::rfcontrol::CurrentSettings>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SetRFSettings<WithAsyncMethod_GetCurrentSettings<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_SetRFSettings : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_SetRFSettings() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::rfcontrol::RFConfig, ::rfcontrol::RFResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::rfcontrol::RFConfig* request, ::rfcontrol::RFResponse* response) { return this->SetRFSettings(context, request, response); }));}
    void SetMessageAllocatorFor_SetRFSettings(
        ::grpc::experimental::MessageAllocator< ::rfcontrol::RFConfig, ::rfcontrol::RFResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::rfcontrol::RFConfig, ::rfcontrol::RFResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_SetRFSettings() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetRFSettings(::grpc::ServerContext* /*context*/, const ::rfcontrol::RFConfig* /*request*/, ::rfcontrol::RFResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* SetRFSettings(
      ::grpc::CallbackServerContext* /*context*/, const ::rfcontrol::RFConfig* /*request*/, ::rfcontrol::RFResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* SetRFSettings(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::rfcontrol::RFConfig* /*request*/, ::rfcontrol::RFResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetCurrentSettings : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_GetCurrentSettings() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::rfcontrol::DeviceQuery, ::rfcontrol::CurrentSettings>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::rfcontrol::DeviceQuery* request, ::rfcontrol::CurrentSettings* response) { return this->GetCurrentSettings(context, request, response); }));}
    void SetMessageAllocatorFor_GetCurrentSettings(
        ::grpc::experimental::MessageAllocator< ::rfcontrol::DeviceQuery, ::rfcontrol::CurrentSettings>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::rfcontrol::DeviceQuery, ::rfcontrol::CurrentSettings>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_GetCurrentSettings() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCurrentSettings(::grpc::ServerContext* /*context*/, const ::rfcontrol::DeviceQuery* /*request*/, ::rfcontrol::CurrentSettings* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetCurrentSettings(
      ::grpc::CallbackServerContext* /*context*/, const ::rfcontrol::DeviceQuery* /*request*/, ::rfcontrol::CurrentSettings* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetCurrentSettings(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::rfcontrol::DeviceQuery* /*request*/, ::rfcontrol::CurrentSettings* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_SetRFSettings<ExperimentalWithCallbackMethod_GetCurrentSettings<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_SetRFSettings<ExperimentalWithCallbackMethod_GetCurrentSettings<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SetRFSettings : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SetRFSettings() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SetRFSettings() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetRFSettings(::grpc::ServerContext* /*context*/, const ::rfcontrol::RFConfig* /*request*/, ::rfcontrol::RFResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetCurrentSettings : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetCurrentSettings() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetCurrentSettings() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCurrentSettings(::grpc::ServerContext* /*context*/, const ::rfcontrol::DeviceQuery* /*request*/, ::rfcontrol::CurrentSettings* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SetRFSettings : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SetRFSettings() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SetRFSettings() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetRFSettings(::grpc::ServerContext* /*context*/, const ::rfcontrol::RFConfig* /*request*/, ::rfcontrol::RFResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetRFSettings(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetCurrentSettings : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetCurrentSettings() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetCurrentSettings() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCurrentSettings(::grpc::ServerContext* /*context*/, const ::rfcontrol::DeviceQuery* /*request*/, ::rfcontrol::CurrentSettings* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetCurrentSettings(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_SetRFSettings : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_SetRFSettings() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SetRFSettings(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_SetRFSettings() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetRFSettings(::grpc::ServerContext* /*context*/, const ::rfcontrol::RFConfig* /*request*/, ::rfcontrol::RFResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* SetRFSettings(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* SetRFSettings(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetCurrentSettings : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_GetCurrentSettings() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetCurrentSettings(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_GetCurrentSettings() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCurrentSettings(::grpc::ServerContext* /*context*/, const ::rfcontrol::DeviceQuery* /*request*/, ::rfcontrol::CurrentSettings* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetCurrentSettings(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetCurrentSettings(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SetRFSettings : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SetRFSettings() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::rfcontrol::RFConfig, ::rfcontrol::RFResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::rfcontrol::RFConfig, ::rfcontrol::RFResponse>* streamer) {
                       return this->StreamedSetRFSettings(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SetRFSettings() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SetRFSettings(::grpc::ServerContext* /*context*/, const ::rfcontrol::RFConfig* /*request*/, ::rfcontrol::RFResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSetRFSettings(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::rfcontrol::RFConfig,::rfcontrol::RFResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetCurrentSettings : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetCurrentSettings() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::rfcontrol::DeviceQuery, ::rfcontrol::CurrentSettings>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::rfcontrol::DeviceQuery, ::rfcontrol::CurrentSettings>* streamer) {
                       return this->StreamedGetCurrentSettings(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetCurrentSettings() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetCurrentSettings(::grpc::ServerContext* /*context*/, const ::rfcontrol::DeviceQuery* /*request*/, ::rfcontrol::CurrentSettings* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetCurrentSettings(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::rfcontrol::DeviceQuery,::rfcontrol::CurrentSettings>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SetRFSettings<WithStreamedUnaryMethod_GetCurrentSettings<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SetRFSettings<WithStreamedUnaryMethod_GetCurrentSettings<Service > > StreamedService;
};

}  // namespace rfcontrol


#endif  // GRPC_rfcontrol_2eproto__INCLUDED
